# Generated by Django 4.0.1 on 2022-01-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bairesdev_project', '0002_rename_news_techcrunch_alter_techcrunch_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechCrunch',
            new_name='News',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
