# Generated by Django 4.0.1 on 2022-01-14 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bairesdev_project', '0003_rename_techcrunch_news_alter_news_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='page',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
