# Generated by Django 4.0.1 on 2022-01-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bairesdev_project', '0005_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
